### PR TITLE
make SQLALCHEMY_DATABASE_URI more generalized

### PR DESCRIPTION
**Pull request by chapmanjacobd**
to support connections on file sockets

looks like this:

```
postgresql+psycopg2://{DATABASE_CREDENTIALS}@/dispatch?host=/file_socket
```

### CODE REVIEW

**Comment by chapmanjacobd** [comment]
ah wait this still won't work because ":" will be there even if you don't specify `port` hmmmm....

**Comment by chapmanjacobd** [comment]
can we override config( default() ) with an empty string ?

**Comment by kevgliss** [comment]
I think this might be easiest to support with a new config item and documentation? Defaulting to the current schematics?

**Comment by chapmanjacobd** [comment]
yes. I agree. something more generic will be better and a breaking change
will allow for a cleaner solution

**Comment by kevgliss** [comment]
Cool, I'm going to close this PR feel free to open another.

**Pull request closed without merging**
