### PR TITLE
Moves signal definitions to its own settings section

### PR DESCRIPTION
**Pull request by mvilanova**

### CODE REVIEW

**Comment by kevgliss** [comment]
Should we remove the general section altogether? I'm not sure why `workflows` would fit in the general section but `signals` would not.

**Comment by mvilanova** [comment]
If we remove the General section, where do we put plugins since they apply to incidents and cases? Same with workflows. I also kept notifications there for when we have support for them in cases. I don't see signals applying to both cases and incidents.

**Comment by kevgliss** [comment]
Should signals be under the case settings then? They map directly to cases, there is no reason they couldn't map directly to incidents in the future, but that is not the current use case.

**Comment by mvilanova** [comment]
Sure, unless you're planning to add more signals-related configuration settings?

**Comment by kevgliss** [comment]
> Sure, unless you're planning to add more signals-related configuration settings?

I can't think of any right now that wouldn't be directly in the signal definition itself.

**Pull request merged**
