### PR TITLE
feat(auth): aws application load balancer plugin

### PR DESCRIPTION
**Pull request by roblambell**
New auth provider for AWS Application Load Balancer :)

docs: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html

### CODE REVIEW

**Comment by mvilanova** [comment]
Looks good @roblambell! We will merge the changes once all the checks pass. Thanks!

**Review by mvilanova — APPROVED** [review]

**Comment by mvilanova** [comment]
@roblambell can you run ruff against the files you touched and upload the changes?

**Comment by roblambell** [comment]
Awesome, thanks @mvilanova! updated 👍

**Comment by mvilanova** [comment]
@roblambell would you mind rebasing the latest changes in master? I'll merge the PR after you're done.

**Pull request merged**
