### PR TITLE
Adds plugin for OpenAI's Generative Artificial Intelligence platform

### PR DESCRIPTION
**Pull request by mvilanova**
Screenshot 2023-03-24 at 1 21 02 PM

### CODE REVIEW

**Comment by wssheldon** [comment]
should we use the python library? 

https://platform.openai.com/docs/libraries/python-bindings

**Review by wssheldon — APPROVED** [review]

**Comment by mvilanova** [comment]
@wssheldon yeah, I was just working on switching to it. chatGPTv4 doesn't seem to be aware of it, apparently :)

**Comment by sara4dev** [comment]
@mvilanova What's the end user experience like with this plugin?

**Comment by mvilanova** [comment]
> What's the end user experience like with this plugin?

@sara4dev the plugin does not change the UX at the moment, but it's there in case collaborators want to experiment with it. We have some ideas on how to leverage it that we will be experimenting with and potentially merge this year. I started a discussion with some of them in case you want to check it out/ contribute to.

**Comment by sara4dev** [comment]
@mvilanova - got it. I would like to contribute in this effort, could you include me in the discussions?

**Pull request merged**
