### PR TITLE
Updates stale workflow to close issues and PRs

### PR DESCRIPTION
**Pull request by mvilanova**

### CODE REVIEW

**Comment by kishorebanala** [comment]
@mvilanova Oops, I committed to wrong repo. I've been trying to do the same for other repo, and have been using this as a reference.

I'll clean up the commit.

**Comment by mvilanova** [comment]
@kishorebanala no worries. If you could remove the commit, that would be great. I'd like to merge the changes to master soon.

**Comment by mvilanova** [comment]
@kishorebanala I removed your commit for you.

**Comment by kishorebanala** [comment]
@mvilanova thanks for cleaning up. I'm about to push, but failed at auth.

**Pull request merged**
